repository:
  has_wiki: false

  delete_branch_on_merge: true

  default_branch: main

  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      restrictions: null
      enforce_admins: false
      required_status_checks:
        strict: true
        contexts:
          - Run "sbt ci-test" on JDK adopt:1.8
          - Run "sbt ci-test" on JDK adopt:1.11
          - Run "sbt ci-test" on JDK adopt:1.15

labels:
  - name: ":beetle: bug"
    color: B60205
    description: Bug fixes
  - name: ":blue_book: documentation"
    color: 1d76db
    description: Documentation changes
  - name: ":broom: cleaning"
    color: BB975B
    description: Removing code
  - name: ":chart_with_upwards_trend: dependency-update"
    color: D3F026
    description: Dependency update (possibly bot-automated)
  - name: ":lipstick: style"
    color: F78BFD
    description: Style or formatting changes
  - name: ":package: refactor"
    color: 382A86
    description: Refactor or renaming changes
  - name: ":rocket: feature"
    color: 642434
    description: New feature or improvement
  - name: ":test_tube: tests"
    color: 86F89E
    description: Test changes (fixing or adding new ones)
  - name: ":warning: breaking"
    color: F3DE0B
    description: Breaking changes to the API
  - name: ":wrench: build"
    color: 4CBAEA
    description: "Changes to the project's build"
