repository:
  has_wiki: false

  delete_branch_on_merge: true

  default_branch: main

  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      restrictions: null
      enforce_admins: false
      required_status_checks:
        strict: true
        contexts:
          - Run "sbt ci-test" on JDK adopt:1.8
          - Run "sbt ci-test" on JDK adopt:1.11
          - Run "sbt ci-test" on JDK adopt:1.15
