addSbtPlugin("com.alejandrohdezma"       % "sbt-scalafmt-defaults" % "0.4.1")
addSbtPlugin("com.alejandrohdezma"       % "sbt-modules"           % "0.1.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.1.16")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.4.3")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"              % "2.2.21")
addSbtPlugin("io.kevinlee"               % "sbt-github-pages"      % "0.6.0")
