name: Deploy GitHub Pages Site

on:
  push:
    branches:
      - "main"
    paths:
      - "modules/site/**"

jobs:
  deploy-site:
    name: Deploy GitHub Pages Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Run `sbt laikaSite`
        uses: alejandrohdezma/actions/scala@v1
        with:
          jvm: openjdk:1.17
          task: laikaSite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}

      - name: Commit changes by `sbt laikaSite`
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Run `sbt laikaSite`
          branch: main
