name: Deploy GitHub Pages Site

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "modules/site/**"

jobs:
  deploy-site:
    name: Deploy GitHub Pages Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          
      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # v3.5.1
        with:
          distribution: "liberica"
          java-version: "17"
          cache: "sbt"

      - name: Run `sbt laikaSite`
        run: sbt laikaSite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}

      - name: Commit changes by `sbt laikaSite`
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Run `sbt laikaSite`
          branch: main
