name: Run Scala Steward on the managed repositories

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to update"
        required: false
        default: ""
  schedule:
    - cron: "0 5 * * *"

jobs:
  run-scala-steward-single-repository:
    name: Run Scala Steward in the selected repository
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.repository != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts the project
        uses: actions/checkout@v2.3.5
      - name: Get the GitHub App installation token
        uses: jnwng/github-app-installation-token-action@v2
        id: generate-token
        with:
          appId: 104853
          installationId: 15336457
          privateKey: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
      - name: Launch Scala Steward in the selected repository
        uses: scala-steward-org/scala-steward-action@v2.13.6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          github-repository: ${{ github.event.inputs.repository }}
          author-email: 80571129+alejandrohdezma-steward[bot]@users.noreply.github.com
          author-name: alejandrohdezma-steward[bot]
  run-scala-steward-all-repos:
    name: Run Scala Steward in all the repositories managed by the GitHub App
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.repository == '')
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts the project
        uses: actions/checkout@v2.3.5
      - name: Get the GitHub App installation token
        uses: jnwng/github-app-installation-token-action@v2
        id: generate-token
        with:
          appId: 104853
          installationId: 15336457
          privateKey: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
      - name: Launch Scala Steward on all repositories managed by the Github App
        uses: scala-steward-org/scala-steward-action@v2.13.6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 80571129+alejandrohdezma-steward[bot]@users.noreply.github.com
          author-name: alejandrohdezma-steward[bot]
          github-app-id: 104853
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
