name: Run Scala Steward on the managed repositories

on: workflow_dispatch

jobs:
  run-scala-steward:
    name: Run Scala Steward
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts the project
        uses: actions/checkout@v2
      - name: Create repos.md file
        uses: mikefarah/yq@v4.2.1
        with:
          cmd: yq read .github/workflows/sync-secrets.yml jobs.sync-secrets.strategy.matrix.repo > repos.md
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
          git-user-signingkey: true
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          repos-file: repos.md
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          sign-commits: true
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
