name: Run Scala Steward on the managed repositories

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to update or `all` for updating every repository managed by the GitHub App"
        required: false
        default: ""
  schedule:
    - cron: "0 5 * * *"

jobs:
  run-scala-steward-single-repository:
    name: Run Scala Steward in the selected repository
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.repository != 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Get the GitHub App installation token
        uses: alejandrohdezma/actions/github-app-token@v1
        id: github_app
        with:
          token: ${{ secrets.GH_APP_TOKEN }}

      - name: Launch Scala Steward in the selected repository
        uses: scala-steward-org/scala-steward-action@0ecbdeebef08cc4146049130c69f9afada6e81c5 # v2.13.7
        with:
          github-token: ${{ steps.github_app.outputs.token }}
          github-repository: alejandrohdezma/${{ github.event.inputs.repository }}
          author-email: 80571129+alejandrohdezma-steward[bot]@users.noreply.github.com
          author-name: alejandrohdezma-steward[bot]

  run-scala-steward-all-repos:
    name: Run Scala Steward in all the repositories managed by the GitHub App
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.repository == 'all')
    runs-on: ubuntu-latest
    steps:
      - name: Get the GitHub App installation token
        uses: alejandrohdezma/actions/github-app-token@v1
        id: github_app
        with:
          token: ${{ secrets.GH_APP_TOKEN }}

      - name: Create `repos.md`
        run: |
          gh api installation/repositories |
            jq -r '.repositories | map(.full_name) | map(select(. != "alejandrohdezma/actions")) | .[] | "- " + .' > 'repos.md'
        env:
          GITHUB_TOKEN: ${{ steps.github_app.outputs.token }}

      - name: Launch Scala Steward on all repositories managed by the Github App
        uses: scala-steward-org/scala-steward-action@0ecbdeebef08cc4146049130c69f9afada6e81c5 # v2.13.7
        with:
          github-token: ${{ steps.github_app.outputs.token }}
          author-email: 80571129+alejandrohdezma-steward[bot]@users.noreply.github.com
          author-name: alejandrohdezma-steward[bot]
          repos-file: repos.md
