name: Run Scala Steward on the managed repositories

on: workflow_dispatch

jobs:
  run-scala-steward:
    name: Run Scala Steward
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
          git-user-signingkey: true
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.12.0
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          sign-commits: true
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
          github-app-id: 104853
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
