name: Sync secrets to all my repositories

on: workflow_dispatch

jobs:
  sync-secrets:
    name: Sync secrets to all my repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts the project
        uses: actions/checkout@v2
      - uses: ./actions/get-repositories
        id: repositories
        with:
          github-app-id: 104853
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
      - name: Spread secrets
        uses: google/secrets-sync-action@v1.4.1
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          secrets: |
            ^ADMIN_GITHUB_TOKEN$
            ^PGP.*
            ^SONATYPE.*
          repositories: ${{ steps.repositories.outputs.repositories }}
          repositories_list_regex: false
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
