name: Sync secrets across repositories

on: workflow_dispatch

jobs:
  sync-secrets:
    name: ${{ matrix.repo }}
    strategy:
      fail-fast: false
      matrix:
        repo:
          - alejandrohdezma/sbt-codecov
          - alejandrohdezma/sbt-ci
          - alejandrohdezma/sbt-fix
          - alejandrohdezma/sbt-github
          - alejandrohdezma/sbt-mdoc-toc
          - alejandrohdezma/sbt-modules
          - alejandrohdezma/sbt-remove-test-from-pom
          - alejandrohdezma/sbt-ci-tag-next-version
          - alejandrohdezma/sbt-scalafix-defaults
          - alejandrohdezma/sbt-scalafmt-defaults
          - alejandrohdezma/sensitive-strings
          - alejandrohdezma/http4s-munit
    runs-on: ubuntu-latest
    steps:
      - name: Spread secrets
        uses: google/secrets-sync-action@v1.4.1
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          secrets: |
            ^ADMIN_GITHUB_TOKEN$
            ^PGP.*
            ^SONATYPE.*
            ^GIT_DEPLOY_KEY$
          repositories: ${{ matrix.repo }}
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
