name: Sync secrets and settings to all my repositories

on:
  push:
    paths:
      - ".github/settings.yml"
      - ".github/workflows/sync.yml"
  workflow_dispatch:

jobs:
  get-repositories:
    name: Get repositories managed by the GitHub App
    runs-on: ubuntu-latest
    steps:
      - name: Get the GitHub App installation token
        uses: alejandrohdezma/actions/alejandrohdezma-steward-token@main
        id: github_app
        with:
          private-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
      - name: Get the repositories where the GitHub App is installed
        uses: actions/github-script@v5
        id: repositories
        with:
          github-token: ${{ steps.github_app.outputs.token }}
          script: return (await github.rest.apps.listReposAccessibleToInstallation()).data.repositories.map(r => r.full_name)
    outputs:
      repositories: ${{ steps.repositories.outputs.result }}
  sync:
    name: ${{ matrix.repo }} - Sync settings, labels and secrets
    runs-on: ubuntu-latest
    needs: get-repositories
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.get-repositories.outputs.repositories) }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.5
      - name: Sync settings to ${{ matrix.repo }}
        uses: mattsb42/repo-manager@v1.1
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          github-repository: ${{ matrix.repo }}
      - name: Sync labels between this repo and ${{ matrix.repo }}
        uses: alejandrohdezma/actions/sync-labels@main
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          destination: ${{ matrix.repo }}
      - name: Sync secrets to ${{ matrix.repo }}
        run: |
          gh secret set PGP_PASSPHRASE -b"${PGP_PASSPHRASE}" --repo ${{ matrix.repo }}
          gh secret set PGP_SECRET -b"${PGP_SECRET}" --repo ${{ matrix.repo }}
          gh secret set SCALA_STEWARD_APP_PRIVATE_KEY -b"${SCALA_STEWARD_APP_PRIVATE_KEY}" --repo ${{ matrix.repo }}
          gh secret set SONATYPE_PASSWORD -b"${SONATYPE_PASSWORD}" --repo ${{ matrix.repo }}
          gh secret set SONATYPE_USERNAME -b"${SONATYPE_USERNAME}" --repo ${{ matrix.repo }}
          gh secret set ADMIN_GITHUB_TOKEN -b"${ADMIN_GITHUB_TOKEN}" --repo ${{ matrix.repo }}
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SCALA_STEWARD_APP_PRIVATE_KEY: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
