name: Publish website

on:
  push:
    branches:
      - main
    paths:
      - site/**
  workflow_dispatch:

jobs:
  gh-release:
    name: Publish website to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.5
      - name: Enable Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          apps: sbt
      - name: Release to GitHub Pages
        run: sbt mdoc publishToGitHubPages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
