name: Publish website

on:
  push:
    branches:
      - main
    paths:
      - site/**
  workflow_dispatch:

jobs:
  gh-release:
    name: Publish website to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Run `sbt generateCiFiles`
        uses: alejandrohdezma/actions/scala@v1
        with:
          jvm: openjdk:1.17
          task: mdoc publishToGitHubPages
